-- VHDL Entity MIPS.MIPS_tb.symbol
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--


ENTITY MCU_tb IS
-- Declarations

END MCU_tb ;

--
-- VHDL Architecture MIPS.MIPS_tb.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:45 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

LIBRARY work;

ARCHITECTURE struct OF MCU_tb IS

   -- Architecture declarations

   -- Internal signal declarations
    SIGNAL clock            : STD_LOGIC;
    SIGNAL reset            : STD_LOGIC;
    SIGNAL ena              : STD_LOGIC;	
	SIGNAL SW				: STD_LOGIC_VECTOR( 7 DOWNTO 0 );
	SIGNAL KEY				: STD_LOGIC_VECTOR( 2 DOWNTO 0 );
	SIGNAL LEDR				: STD_LOGIC_VECTOR( 7 DOWNTO 0 );
	SIGNAL HEX0, HEX1		: STD_LOGIC_VECTOR( 6 DOWNTO 0 );
	SIGNAL HEX2, HEX3		: STD_LOGIC_VECTOR( 6 DOWNTO 0 );
	SIGNAL HEX4, HEX5		: STD_LOGIC_VECTOR( 6 DOWNTO 0 );
	SIGNAL BT_OUTMOD		: STD_LOGIC;


   -- Component Declarations
   COMPONENT MCU
	GENERIC ( ALIGNMENT : BOOLEAN ); -- WORD/BYTE alignment: FALSE = QUARTUS ; TRUE = ModelSim
	PORT( reset, clock, ena		 :IN STD_LOGIC; 
	-- GPIO
		SW						: IN  STD_LOGIC_VECTOR( 7  DOWNTO 0 );
		KEY						: IN  STD_LOGIC_VECTOR( 2  DOWNTO 0 );
		LEDR					: OUT STD_LOGIC_VECTOR( 7  DOWNTO 0 );
		HEX0, HEX1				: OUT STD_LOGIC_VECTOR( 6  DOWNTO 0 );
		HEX2, HEX3				: OUT STD_LOGIC_VECTOR( 6  DOWNTO 0 );
		HEX4, HEX5				: OUT STD_LOGIC_VECTOR( 6  DOWNTO 0 ); 
		BT_OUTMOD				: OUT STD_LOGIC );	
   END COMPONENT;
   
   COMPONENT MCU_tester
	GENERIC ( ALIGNMENT : BOOLEAN ); -- WORD/BYTE alignment: FALSE = QUARTUS ; TRUE = ModelSim
	PORT( reset, clock, ena		 :OUT STD_LOGIC; 
	-- GPIO
		SW						: OUT STD_LOGIC_VECTOR( 7  DOWNTO 0 );
		KEY						: OUT STD_LOGIC_VECTOR( 2  DOWNTO 0 );
		LEDR					: IN  STD_LOGIC_VECTOR( 7  DOWNTO 0 );
		HEX0, HEX1				: IN  STD_LOGIC_VECTOR( 6  DOWNTO 0 );
		HEX2, HEX3				: IN  STD_LOGIC_VECTOR( 6  DOWNTO 0 );
		HEX4, HEX5				: IN  STD_LOGIC_VECTOR( 6  DOWNTO 0 );
		BT_OUTMOD				: IN  STD_LOGIC	);
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : MCU USE ENTITY work.MCU;
   FOR ALL : MCU_tester USE ENTITY work.MCU_tester;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_0 : MCU
   	  GENERIC MAP ( ALIGNMENT => TRUE )
      PORT MAP (
         reset           => reset,
         clock           => clock,
		 ena             => ena,
		 SW			     =>	SW,
		 KEY             =>	KEY,
		 LEDR            =>	LEDR,
		 HEX0      		 =>	HEX0, 
		 HEX1      		 =>	HEX1,	
		 HEX2      		 =>	HEX2,
		 HEX3		     =>	HEX3,			
		 HEX4 		     =>	HEX4,
		 HEX5  		     =>	HEX5, 
		 BT_OUTMOD  	 =>	BT_OUTMOD );
		 
   U_1 : MCU_tester
 	  GENERIC MAP ( ALIGNMENT => TRUE )  
      PORT MAP (
         reset           => reset,
         clock           => clock,
		 ena             => ena,
		 SW			     =>	SW,
		 KEY             =>	KEY,
		 LEDR            =>	LEDR,
		 HEX0      		 =>	HEX0, 
		 HEX1      		 =>	HEX1,	
		 HEX2      		 =>	HEX2,
		 HEX3		     =>	HEX3,			
		 HEX4 		     =>	HEX4,
		 HEX5  		     =>	HEX5, 
		 BT_OUTMOD  	 =>	BT_OUTMOD );
		 
END struct;
