-- VHDL Entity MIPS.MIPS_tester.interface
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;

ENTITY MCU_tester IS
	GENERIC ( ALIGNMENT : BOOLEAN := TRUE ); -- WORD/BYTE alignment: FALSE = QUARTUS ; TRUE = ModelSim
	PORT( reset, clock, ena		 :OUT STD_LOGIC; 
	-- GPIO
		SW						: OUT STD_LOGIC_VECTOR( 7  DOWNTO 0 );
		KEY						: OUT STD_LOGIC_VECTOR( 2  DOWNTO 0 );
		LEDR					: IN  STD_LOGIC_VECTOR( 7  DOWNTO 0 );
		HEX0, HEX1				: IN  STD_LOGIC_VECTOR( 6  DOWNTO 0 );
		HEX2, HEX3				: IN  STD_LOGIC_VECTOR( 6  DOWNTO 0 );
		HEX4, HEX5				: IN  STD_LOGIC_VECTOR( 6  DOWNTO 0 ); 
		BT_OUTMOD				: IN  STD_LOGIC );	
		
-- Declarations

END MCU_tester ;

--
-- VHDL Architecture MIPS.MIPS_tester.struct
--
-- Created:
--          by - kolaman.UNKNOWN (KOLAMAN-PC)
--          at - 09:22:44 17/02/2013
--
-- Generated by Mentor Graphics' HDL Designer(TM) 2011.1 (Build 18)
--
LIBRARY IEEE;
USE IEEE.STD_LOGIC_1164.ALL;
USE IEEE.STD_LOGIC_ARITH.ALL;


ARCHITECTURE struct OF MCU_tester IS

   -- Architecture declarations

   -- Internal signal declarations


   -- ModuleWare signal declarations(v1.9) for instance 'U_0' of 'clk'
   SIGNAL mw_U_0clk : std_logic;
   SIGNAL mw_U_0disable_clk : boolean := FALSE;

   -- ModuleWare signal declarations(v1.9) for instance 'U_1' of 'pulse'
   SIGNAL mw_U_1pulse : std_logic :='0';

BEGIN
	ena 	<= '1';
	SW  	<= X"00", X"01" AFTER 1000 ns;--, X"02" AFTER 240000 ns;
	KEY(0)  <= '1', '0' AFTER 3250000 ns, '1' AFTER 3270000 ns, '0' AFTER 5500000 ns, '1' AFTER 5700000 ns, '0' AFTER 8941250 ns, '1' AFTER 8950000 ns;		
	KEY(1)  <= '1', '0' AFTER 5550000 ns, '1' AFTER 5700000 ns, '0' AFTER 6450000 ns, '1' AFTER 6800000 ns, '0' AFTER 8941250 ns, '1' AFTER 8950000 ns;
	KEY(2)  <= '1', '0' AFTER 2450000 ns, '1' AFTER 2500000 ns, '0' AFTER 8941250 ns, '1' AFTER 8950000 ns, '0' AFTER 9500000 ns, '1' AFTER 9700000 ns;		

   -- ModuleWare code(v1.9) for instance 'U_0' of 'clk'
   u_0clk_proc: PROCESS
   BEGIN
      WHILE NOT mw_U_0disable_clk LOOP
         mw_U_0clk <= '0', '1' AFTER 12.5 ns;
         WAIT FOR 25 ns;
      END LOOP;
      WAIT;
   END PROCESS u_0clk_proc;
   mw_U_0disable_clk <= TRUE AFTER 50000000 ns;
   clock <= mw_U_0clk;

   -- ModuleWare code(v1.9) for instance 'U_1' of 'pulse'
   reset <= NOT mw_U_1pulse;
   u_1pulse_proc: PROCESS
   BEGIN
      mw_U_1pulse <= 
         '0',
         '1' AFTER 120 ns,
         '0' AFTER 270 ns;
      WAIT for 1000 ns;
      mw_U_1pulse <= 
         '0',
         '1' AFTER 380 ns,
         '0' AFTER 22170 ns,	
         '1' AFTER 59000 ns,	
         '0' AFTER 59200 ns;			 
      WAIT;		 
    END PROCESS u_1pulse_proc;

   -- Instance port mappings.

END struct;
